version: '3.8'

services:
  db_catalog:
    image: postgres:14
    container_name: postgres_db_catalog
    env_file:
      - ../.env
    volumes:
      - postgres_data_catalog:/var/lib/postgresql/data
    networks:
      - portfolio_network_catalog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_catalog:
    image: redis:6
    container_name: redis_catalog
    networks:
      - portfolio_network_catalog

  web_catalog:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_catalog
    command: sh -c "/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../app:/app
      - static_catalog:/app/core/staticfiles
      - media_catalog:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      db_catalog:
        condition: service_healthy
      redis_catalog:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - portfolio_network_catalog

  telegram_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_catalog
    command: python manage.py bot
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    depends_on:
      - db_catalog
      - web_catalog
    networks:
      - portfolio_network_catalog

networks:
  portfolio_network_catalog:
    driver: bridge

volumes:
  postgres_data_catalog:
  static_catalog:
  media_catalog:
